# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170922_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='curse',
            new_name='course',
        ),
    ]
