# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170923_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userid',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
