# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_profile_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
