# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_profile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborators',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
