# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_colaborators_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
