# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_colaborators_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='userid',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
