# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_labels_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectType',
            field=models.CharField(choices=[(b'sw', b'software'), (b'hw', b'hardware'), (b'ms', b'music'), (b'ar', b'art'), (b'sp', b'sport'), (b'ot', b'other')], default=b'ot', max_length=2),
        ),
    ]
