# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20170923_1004'),
        ('projects', '0008_auto_20170923_1359'),
    ]

    operations = [
    ]
