# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-23 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20170923_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
