# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20170923_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectType',
            field=models.CharField(choices=[('sw', 'software'), ('hw', 'hardware'), ('ms', 'music'), ('ar', 'art'), ('sp', 'sport'), ('ot', 'other')], default='ot', max_length=2),
        ),
    ]
