# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20170923_1359'),
        ('projects', '0009_auto_20170923_1501'),
    ]

    operations = [
    ]
