# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_merge_20170923_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectType',
            field=models.CharField(choices=[('sw', 'software'), ('hw', 'hardware'), ('ms', 'music'), ('ar', 'art'), ('sp', 'sport'), ('ot', 'other')], default='ot', max_length=2),
        ),
    ]
