# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_merge_20170923_1955'),
        ('projects', '0009_merge_20170923_1606'),
    ]

    operations = [
    ]
