# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_merge_20170923_1955'),
        ('projects', '0011_auto_20170924_0055'),
    ]

    operations = [
    ]
