# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_merge_20170924_0237'),
        ('projects', '0013_merge_20170924_0411'),
    ]

    operations = [
    ]
