# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_merge_20170924_0411'),
        ('projects', '0013_merge_20170924_0237'),
    ]

    operations = [
    ]
