# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_merge_20170924_0900'),
        ('projects', '0014_merge_20170924_1128'),
    ]

    operations = [
    ]
