# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_merge_20170924_1007'),
        ('projects', '0015_merge_20170924_1135'),
    ]

    operations = [
    ]
